#!/bin/sh
##SBATCH -q debug
#SBATCH -t 01:30:00
#SBATCH -A gsienkf  
##SBATCH -A isp-1
#SBATCH -N 40    
#SBATCH -J ufs_enkf_psonly
#SBATCH -e ufs_enkf_psonly.err
#SBATCH -o ufs_enkf_psonly.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='hera'

export fg_proc=$corespernode 
export fg_threads=1
export enkf_threads=2 
export write_groups=4
# 40 cores per node 
export write_tasks=1 
export layout="3, 2"
