#!/bin/sh
##SBATCH -q urgent
#SBATCH -t 00:30:00
##SBATCH -A gsienkf
#SBATCH -A da-cpu  
#SBATCH -N 20  
#SBATCH --ntasks-per-node=80
#SBATCH -p hercules
#SBATCH -J C96_enkf_psonly
#SBATCH -e C96_enkf_psonly.err
#SBATCH -o C96_enkf_psonly.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='hercules'

export fg_proc=$corespernode
export fg_threads=1 
export enkf_threads=16
export write_groups=8
export write_tasks=1 
export layout="3, 4"
